apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:           
        app: client
    spec:
      containers:
        - name: client
          image: localhost:5000/client:latest
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: client-srv
spec:
  type: NodePort
  selector:
    app: client        
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80   
      nodePort: 31515
