apiVersion: apps/v1
kind: Deployment
metadata:
  name: envent-bus-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: envent
  template:
    metadata:
      labels:          
        app: envent
    spec:
      containers:
        - name: envent
          image: localhost:5000/envent-bus:latest
          ports:
            - containerPort: 4005
---
apiVersion: v1
kind: Service
metadata:
  name: envent-bus-srv
spec:
  type: NodePort
  selector:
    app: client
  ports:
    - protocol: TCP
      port: 4005
      targetPort: 4005
      nodePort: 31517
